services:
  - type: web
    name: todo_list_frontend

    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://todo-list-backend-hjk1.onrender.com/api/$1

      - type: rewrite
        source: /(.*)
        destination: /$1
