services:
  - type: web
    name: todo_list_frontend

    routes:
      - type: rewrite
        source: /api/v1/(.*)
        destination: https://todo-list-backend-hjk1.onrender.com/api/v1/$1

      - type: rewrite
        source: /(.*)
        destination: /$1
